# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `omniauth-hack_club` gem.
# Please instead update this file by running `bin/tapioca gem omniauth-hack_club`.


# pkg:gem/omniauth-hack_club#lib/omniauth-hack_club/version.rb:3
module OmniAuth; end

# pkg:gem/omniauth-hack_club#lib/omniauth-hack_club/version.rb:4
module OmniAuth::HackClub; end

# pkg:gem/omniauth-hack_club#lib/omniauth-hack_club/version.rb:5
OmniAuth::HackClub::VERSION = T.let(T.unsafe(nil), String)

# pkg:gem/omniauth-hack_club#lib/omniauth/strategies/hack_club.rb:6
module OmniAuth::Strategies; end

# pkg:gem/omniauth-hack_club#lib/omniauth/strategies/hack_club.rb:7
class OmniAuth::Strategies::HackClub < ::OmniAuth::Strategies::OAuth2
  # pkg:gem/omniauth-hack_club#lib/omniauth/strategies/hack_club.rb:56
  def callback_url; end

  # pkg:gem/omniauth-hack_club#lib/omniauth/strategies/hack_club.rb:23
  def client; end

  # pkg:gem/omniauth-hack_club#lib/omniauth/strategies/hack_club.rb:52
  def identity; end

  # pkg:gem/omniauth-hack_club#lib/omniauth/strategies/hack_club.rb:48
  def raw_info; end
end

# pkg:gem/omniauth-hack_club#lib/omniauth/strategies/hack_club.rb:8
OmniAuth::Strategies::HackClub::PRODUCTION_SITE = T.let(T.unsafe(nil), String)

# pkg:gem/omniauth-hack_club#lib/omniauth/strategies/hack_club.rb:9
OmniAuth::Strategies::HackClub::STAGING_SITE = T.let(T.unsafe(nil), String)
